---
apiVersion: v2
appVersion: 1.19.2
description: FreshRSS is a self-hosted RSS feed aggregator
name: freshrss
version: 6.5.1
kubeVersion: ">=1.19.0-0"
keywords:
  - freshrss
  - rss
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/freshrss
icon: https://avatars.githubusercontent.com/u/9414285?s=200&v=4
sources:
  - https://github.com/FreshRSS/FreshRSS
  - https://hub.docker.com/r/linuxserver/freshrss
maintainers:
  - name: npawelek
    email: nathan@nathanpawelek.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded app to 1.19.2.
    - kind: changed
      description: Support only Kubernetes 1.19+.
