---
apiVersion: v2
appVersion: v0.14.0
description: Music streaming server / subsonic server API implementation
name: gonic
version: 6.5.0
kubeVersion: ">=1.16.0-0"
keywords:
  - music
  - subsonic
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/gonic
icon: https://raw.githubusercontent.com/sentriz/gonic/master/.github/logo.png
sources:
  - https://github.com/sentriz/gonic
  - https://hub.docker.com/r/sentriz/gonic
maintainers:
  - name: Skyler Mäntysaari
    url: https://github.com/samip5
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded app to 0.14.0.
