---
apiVersion: v2
appVersion: 2.2.2-1
description: Container for protonmail bridge to work on the network.
name: protonmail-bridge
version: 5.5.0
kubeVersion: ">=1.16.0-0"
keywords:
  - protonmail
  - protonmail-bridge
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/protonmail-bridge
icon: https://raw.githubusercontent.com/ProtonMail/proton-bridge/master/dist/bridge.ico
sources:
  - https://github.com/shenxn/protonmail-bridge-docker
  - https://hub.docker.com/r/shenxn/protonmail-bridge
maintainers:
  - name: Eagleman7
    email: my@email.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgrade app to 2.2.2-1.
